-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.refresh_token
(
    refresh_token_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    expired_at timestamp without time zone NOT NULL,
    create_at timestamp without time zone NOT NULL,
    revoked boolean NOT NULL,
    CONSTRAINT refresh_token_pkey PRIMARY KEY (refresh_token_id)
);

CREATE TABLE IF NOT EXISTS public.rols
(
    rol_id serial NOT NULL,
    user_id uuid NOT NULL,
    rol rols_user NOT NULL,
    CONSTRAINT rols_pkey PRIMARY KEY (rol_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    username character varying(30) COLLATE pg_catalog."default" NOT NULL,
    email character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.refresh_token
    ADD CONSTRAINT fk_user_refreshtoken FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rols
    ADD CONSTRAINT fk_user_rols FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;