-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

CREATE TABLE IF NOT EXISTS public.asset_media
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    owner_id uuid NOT NULL,
    owner_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    cloud_public_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    format character varying(10) COLLATE pg_catalog."default" NOT NULL,
    resource_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    storage_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    bytes bigint NOT NULL,
    width integer,
    height integer,
    url text COLLATE pg_catalog."default" NOT NULL,
    secure_url text COLLATE pg_catalog."default" NOT NULL,
    "position" integer DEFAULT 0,
    is_cover boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    deleted_at timestamp without time zone,
    CONSTRAINT asset_media_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.catalog_items
(
    catalog_id uuid NOT NULL,
    product_id uuid NOT NULL,
    custom_label text COLLATE pg_catalog."default",
    create_at timestamp without time zone DEFAULT now(),
    CONSTRAINT catalog_items_pk PRIMARY KEY (catalog_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.catalogs
(
    catalog_id uuid NOT NULL DEFAULT gen_random_uuid(),
    code text COLLATE pg_catalog."default" NOT NULL,
    slug text COLLATE pg_catalog."default" NOT NULL,
    name_catalog character varying(30) COLLATE pg_catalog."default" NOT NULL,
    type_catalog character varying(10) COLLATE pg_catalog."default" NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    visible boolean DEFAULT true,
    CONSTRAINT catalogs_pkey PRIMARY KEY (catalog_id)
);

CREATE TABLE IF NOT EXISTS public.email_verification_token
(
    email_verification_token_id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    consumed_at timestamp without time zone,
    expired_at timestamp without time zone,
    CONSTRAINT email_verification_token_pkey PRIMARY KEY (email_verification_token_id)
);

CREATE TABLE IF NOT EXISTS public.flyway_schema_history
(
    installed_rank integer NOT NULL,
    version character varying(50) COLLATE pg_catalog."default",
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    script character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    checksum integer,
    installed_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    installed_on timestamp without time zone NOT NULL DEFAULT now(),
    execution_time integer NOT NULL,
    success boolean NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE IF NOT EXISTS public.inventories
(
    inventory_id integer NOT NULL DEFAULT nextval('inventorys_inventory_id_seq'::regclass),
    quantity integer NOT NULL,
    warehouse_location text COLLATE pg_catalog."default",
    last_updated timestamp without time zone DEFAULT now(),
    listing_id uuid NOT NULL,
    CONSTRAINT inventorys_pkey PRIMARY KEY (inventory_id),
    CONSTRAINT unique_inventory_per_listings UNIQUE (listing_id)
);

CREATE TABLE IF NOT EXISTS public.listings
(
    listing_id uuid NOT NULL,
    product_id uuid NOT NULL,
    price numeric(10, 2),
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'USD'::text,
    is_active boolean DEFAULT true,
    create_at timestamp without time zone DEFAULT now(),
    update_at timestamp without time zone DEFAULT now(),
    status_review character varying(10) COLLATE pg_catalog."default" NOT NULL,
    status_publication character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT listings_pkey PRIMARY KEY (listing_id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_item_id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL,
    listing_id uuid NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    order_date timestamp without time zone DEFAULT now(),
    status text COLLATE pg_catalog."default" DEFAULT 'pending'::text,
    total_amount numeric(10, 2) NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL,
    amount numeric(10, 2) NOT NULL,
    currency text COLLATE pg_catalog."default" DEFAULT 'USD'::text,
    method_pay text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" DEFAULT 'pending'::text,
    paid_at timestamp without time zone DEFAULT now(),
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    permission_id uuid NOT NULL,
    permission_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT permissions_pkey PRIMARY KEY (permission_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id uuid NOT NULL,
    name_product character varying(20) COLLATE pg_catalog."default" NOT NULL,
    short_description text COLLATE pg_catalog."default" NOT NULL,
    long_description text COLLATE pg_catalog."default",
    model character varying(30) COLLATE pg_catalog."default" NOT NULL,
    sku text COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (product_id),
    CONSTRAINT products_sku_unique_key UNIQUE (user_id, sku)
);

CREATE TABLE IF NOT EXISTS public.references_products
(
    reference_id uuid NOT NULL DEFAULT gen_random_uuid(),
    product_id uuid NOT NULL,
    reference_type text COLLATE pg_catalog."default",
    target_product_id uuid NOT NULL,
    CONSTRAINT references_products_pkey PRIMARY KEY (reference_id)
);

CREATE TABLE IF NOT EXISTS public.refresh_token
(
    refresh_token_id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    expired_at timestamp without time zone NOT NULL,
    create_at timestamp without time zone NOT NULL,
    revoked boolean NOT NULL,
    CONSTRAINT refresh_token_pkey PRIMARY KEY (refresh_token_id),
    CONSTRAINT refresh_token_hash_key UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS public.rol_permissions
(
    rol_permission_id serial NOT NULL,
    rol_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    CONSTRAINT rol_permissions_pkey PRIMARY KEY (rol_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.rols
(
    rol_id uuid NOT NULL,
    rol character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT rols_pkey PRIMARY KEY (rol_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL,
    username character varying(30) COLLATE pg_catalog."default" NOT NULL,
    email character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    auth_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::text,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.users_rols
(
    user_rol_id serial NOT NULL,
    user_id uuid NOT NULL,
    rol_id uuid NOT NULL,
    CONSTRAINT users_rols_pkey PRIMARY KEY (user_id, rol_id)
);

ALTER TABLE IF EXISTS public.catalog_items
    ADD CONSTRAINT fk_catalog_items_catalog FOREIGN KEY (catalog_id)
    REFERENCES public.catalogs (catalog_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.catalog_items
    ADD CONSTRAINT fk_catalog_items_product FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_catalog_items_product
    ON public.catalog_items(product_id);


ALTER TABLE IF EXISTS public.email_verification_token
    ADD CONSTRAINT fk_user_email_verification_token FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.listings
    ADD CONSTRAINT fk_listings_products FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_listings_product
    ON public.listings(product_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT fk_order_items_listing FOREIGN KEY (listing_id)
    REFERENCES public.listings (listing_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_order_items_listing
    ON public.order_items(listing_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_order_items_order
    ON public.order_items(order_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_users_orders FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk_payments_orders FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fk_products_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.references_products
    ADD CONSTRAINT fk_references_products FOREIGN KEY (product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.refresh_token
    ADD CONSTRAINT fk_user_refreshtoken FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rol_permissions
    ADD CONSTRAINT fk_permission_permissions FOREIGN KEY (permission_id)
    REFERENCES public.permissions (permission_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rol_permissions
    ADD CONSTRAINT fk_rol_rols FOREIGN KEY (rol_id)
    REFERENCES public.rols (rol_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users_rols
    ADD CONSTRAINT fk_rol_users FOREIGN KEY (rol_id)
    REFERENCES public.rols (rol_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users_rols
    ADD CONSTRAINT fk_user_rols FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;