spring:
  application:
    name: 01-WebFlux
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/microservicedb
    username: br7forlife
    password: 1234

  flyway:
    enabled: false
    url: ${SPRING_DATASOURCE_URL} 
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    locations:
    - classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

refresh-token:
  ttl: 30d